resources:
  - name: johnCabGitRepo
    type: GitRepo
    configuration:
      gitProvider: johnca_github
      path: john-cab/pipelines
      branches:
        include: master
pipelines:
  - name: testPipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: '1.0.$run_number'
          ArtIP: $(echo ${int_ArtifactoryUnified_url}|awk -F '/' '{print $3}'|awk -F ':' '{print $1}')
